'use client';

import { useState, type FormEvent } from 'react';
import Link from 'next/link';
import { ApiError } from '@/lib/api-client';
import { useAcceptFamilyLink } from '@/hooks/use-family-children';
import { LoadingSpinner } from '@/components/ui/LoadingSpinner';
import { PageHeader } from '@/components/ui/PageHeader';

/**
 * /settings/family — child / second-parent landing for accepting a
 * link code. Section 3 + Section 5B of the persona-registration design.
 *
 * The code is the 8-char alphanumeric token generated by the inviter's
 * /family/children/:id/send-link call. We display it formatted as
 * XXXX-XXXX with an auto-dash on input so it's friendlier to type;
 * the API itself accepts the dashless canonical form, so we strip on
 * submit. POST /family/link returns the linked family_child row on
 * success.
 */
export default function SettingsFamilyPage() {
  const accept = useAcceptFamilyLink();
  const [raw, setRaw] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);

  function onChange(next: string) {
    setError(null);
    setSuccess(null);
    // Strip everything but A-Z and 0-9, uppercase, then re-insert
    // a dash after the fourth char if there are 5+ characters.
    const cleaned = next
      .toUpperCase()
      .replace(/[^A-Z0-9]/g, '')
      .slice(0, 8);
    setRaw(cleaned);
  }

  async function onSubmit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault();
    if (raw.length !== 8) {
      setError('Codes are 8 characters.');
      return;
    }
    try {
      await accept.mutateAsync({ code: raw });
      setSuccess("You're now connected to the inviting family.");
      setRaw('');
    } catch (err) {
      if (err instanceof ApiError && err.status === 404) {
        setError('Invalid or expired code. Please try again.');
      } else if (err instanceof ApiError && err.status === 429) {
        setError('Too many attempts. Try again in a few minutes.');
      } else {
        const message = err instanceof Error ? err.message : 'Could not link.';
        setError(message);
      }
    }
  }

  // Display formatted as XXXX-XXXX — split after position 4.
  const display = raw.length > 4 ? `${raw.slice(0, 4)}-${raw.slice(4)}` : raw;

  return (
    <div className="mx-auto w-full max-w-xl">
      <PageHeader
        title="Family"
        description="Connect to a family that's invited you."
        actions={
          <Link
            href="/family"
            className="text-sm font-medium text-campus-700 hover:text-campus-600"
          >
            My family →
          </Link>
        }
      />

      <section className="rounded-card border border-gray-200 bg-white p-5 shadow-sm">
        <h2 className="text-base font-semibold text-gray-900">Link to a Family</h2>
        <p className="mt-1 text-sm text-gray-600">
          Enter the 8-character code you received in your invitation email.
        </p>

        <form onSubmit={onSubmit} className="mt-4 flex flex-col gap-3">
          <div>
            <label htmlFor="link-code" className="block text-xs font-medium text-gray-700">
              Code
            </label>
            <input
              id="link-code"
              name="link-code"
              type="text"
              value={display}
              onChange={(e) => onChange(e.target.value)}
              placeholder="ABCD-1234"
              autoComplete="off"
              autoCapitalize="characters"
              spellCheck={false}
              aria-invalid={!!error}
              aria-describedby={
                error ? 'link-code-error' : success ? 'link-code-success' : undefined
              }
              className={
                'mt-1 block w-full rounded-md border bg-white px-3 py-2 text-center font-mono text-lg uppercase tracking-[0.3em] text-gray-900 shadow-sm placeholder:font-mono placeholder:text-gray-300 focus:border-campus-500 focus:outline-none focus:ring-2 focus:ring-campus-500 ' +
                (error ? 'border-red-300' : 'border-gray-300')
              }
            />
            {error && (
              <p id="link-code-error" className="mt-1 text-xs text-red-600">
                {error}
              </p>
            )}
            {success && (
              <p id="link-code-success" className="mt-1 text-xs text-green-700">
                {success}
              </p>
            )}
          </div>

          <button
            type="submit"
            disabled={accept.isPending || raw.length !== 8}
            className="inline-flex items-center justify-center gap-2 rounded-md bg-campus-700 px-4 py-2 text-sm font-semibold text-white shadow-sm transition-colors hover:bg-campus-600 disabled:opacity-60"
          >
            {accept.isPending && <LoadingSpinner size="sm" />}
            <span>{accept.isPending ? 'Linking…' : 'Link'}</span>
          </button>
        </form>
      </section>

      <p className="mt-6 text-center text-xs text-gray-400">
        Didn&rsquo;t get a code? Ask your parent to resend the invitation from their family page.
      </p>
    </div>
  );
}
