import { Module } from '@nestjs/common';
import { TenantModule } from '../tenant/tenant.module';
import { IamModule } from '../iam/iam.module';
import { KafkaModule } from '../kafka/kafka.module';
import { LockerService } from './locker.service';
import { MedicalExemptionService } from './medical-exemption.service';
import { ReportingPeriodService } from './reporting-period.service';
import { SisTranscriptsController } from './sis-transcripts.controller';
import { StudentAwardService } from './student-award.service';
import { TranscriptService } from './transcript.service';
import { TransferService } from './transfer.service';

/**
 * SIS Transcripts Module — Phase 2 Cycle 13 sub-cycle c (P2-13c).
 *
 * Ships 6 services + 1 controller + ~22 endpoints under STU-001 / 004 /
 * 005 / 007.
 *
 * Three structural keystones:
 *   1. FROZEN TRANSCRIPT SNAPSHOT — sis_transcript_courses are written
 *      ONCE at TranscriptService.generate() by snapshotting cls_grades
 *      joined to sis_classes + sis_courses + sis_terms +
 *      sis_academic_years. The rows are NEVER re-read from cls_grades.
 *      A re-grade downstream creates a NEW transcript with fresh
 *      frozen rows; it does NOT rewrite the existing rows. ADR-010
 *      immutability for the legal student record.
 *   2. LOCKER COMBINATION ENCRYPTION — sis_lockers.combination_encrypted
 *      stores AES-256-GCM ciphertext in the project standard wire
 *      format base64(iv).base64(tag).base64(ciphertext). The plaintext
 *      combination is generated by LockerService.assign() and returned
 *      ONCE in the response, never persisted in plaintext. Year-end
 *      bulk-clear releases every ASSIGNED locker in one tx, clearing
 *      assigned_to_student_id + assigned_at + academic_year +
 *      combination_encrypted atomically per the assignment_chk
 *      lockstep.
 *   3. REPORTING PERIOD STRICT TRANSITIONS — ReportingPeriodService
 *      enforces UPCOMING -> OPEN -> GRADING_CLOSED -> PUBLISHED as
 *      the only forward path. Skipping forward and walking backward
 *      are both refused. The PUBLISHED row stamps published_at
 *      atomically per the published_chk lockstep.
 *
 * Cross-cycle integration:
 *   - TranscriptService.submitRequest with feeAmount set creates a
 *     matching pay_invoice (Cycle 6) so the family pays via the
 *     normal billing flow.
 *   - StudentAwardService.bulkHonorRoll reads sis_student_gpa_snapshots
 *     (P2-13b) to find qualifying students.
 *   - LockerService stamps assigned_to_student_id as a soft FK to
 *     sis_students per ADR-001 / 020.
 *
 * Permission codes (already in catalogue):
 *   - STU-001 Student Profiles — medical exemptions
 *   - STU-004 Withdrawal & Transfer — transfer records
 *   - STU-005 Graduation Management — transcripts + reporting periods
 *     + awards
 *   - STU-007 Locker Management — lockers
 */
@Module({
  imports: [TenantModule, IamModule, KafkaModule],
  providers: [
    TranscriptService,
    TransferService,
    LockerService,
    ReportingPeriodService,
    StudentAwardService,
    MedicalExemptionService,
  ],
  controllers: [SisTranscriptsController],
  exports: [
    TranscriptService,
    TransferService,
    LockerService,
    ReportingPeriodService,
    StudentAwardService,
    MedicalExemptionService,
  ],
})
export class SisTranscriptsModule {}
