-- Bidirectional family-link feature — adds FAMILY_INVITE to the
-- platform_invitations type CHECK constraint.
--
-- The persona-registration schema only allowed:
--   EMPLOYEE, CHILD_LINK, PARENT_LINK, SUBSTITUTE
-- which covered the school-issued-to-employee, parent-issued-for-
-- existing-child, school-issued-to-parent, and substitute-onboarding
-- flows respectively. The bidirectional family-link work adds a
-- fifth type:
--
--   FAMILY_INVITE — generated by a PARENT for an unknown child.
--     metadata.familyId references the inviter's platform_families
--     row. Any authenticated user who accepts the code joins that
--     family as a LINKED platform_family_children row (no
--     family_members write — they're a child, not an HoH/spouse).
--
-- CHILD_LINK keeps its existing meaning (parent issues for a
-- specific PLACEHOLDER family_child via the send-link API), AND
-- gains a new meaning when there's no metadata.familyChildId:
-- a CHILD generates the code, a PARENT accepts it, and the parent's
-- family gains the child via auto-match or a fresh LINKED row.
-- That second meaning is dispatched in service code, not via a
-- new type, because the wire shape stays identical.
--
-- Idempotent — re-runs on environments that already have the
-- widened constraint are no-ops.

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'platform_invitations_type_check'
  ) THEN
    ALTER TABLE platform.platform_invitations
      DROP CONSTRAINT platform_invitations_type_check;
  END IF;
  ALTER TABLE platform.platform_invitations
    ADD CONSTRAINT platform_invitations_type_check
    CHECK (type IN ('EMPLOYEE', 'CHILD_LINK', 'PARENT_LINK', 'SUBSTITUTE', 'FAMILY_INVITE'));
END $$;
