-- Guardian-invite feature — adds GUARDIAN_INVITE to the
-- platform_invitations type CHECK constraint.
--
-- Semantics:
--   GUARDIAN_INVITE — generated by a PARENT on /family. metadata
--     carries familyId of the inviter's family. Whoever accepts is
--     added as a PARENT (HEAD_OF_HOUSEHOLD's co-parent) on the
--     family via platform_family_members. They gain full read/write
--     on every child in that family — the family becomes shared.
--
-- The existing FAMILY_INVITE type stays for parent → child code
-- flows; GUARDIAN_INVITE specifically targets adult co-parents.
-- Acceptance dispatches inside acceptLinkCode based on the type,
-- so the wire token shape doesn't need to change.
--
-- Idempotent — drops the previous CHECK constraint (if any) and
-- recreates it with the widened set. Re-running on environments
-- that already have GUARDIAN_INVITE is a no-op.

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'platform_invitations_type_check'
  ) THEN
    ALTER TABLE platform.platform_invitations
      DROP CONSTRAINT platform_invitations_type_check;
  END IF;
  ALTER TABLE platform.platform_invitations
    ADD CONSTRAINT platform_invitations_type_check
    CHECK (type IN (
      'EMPLOYEE', 'CHILD_LINK', 'PARENT_LINK', 'SUBSTITUTE',
      'FAMILY_INVITE', 'GUARDIAN_INVITE'
    ));
END $$;
